SELECT 
  MACHINE.NAME AS SYSTEM_NAME, 
  SYSTEM_DESCRIPTION, 
  MACHINE.IP, 
  MACHINE.MAC, 
  MACHINE.ID AS TOPIC_ID
FROM 
  MACHINE
LEFT JOIN 
  OSUPGRADE_READINESS ON OSUPGRADE_READINESS.ID = MACHINE.ID
WHERE 
  OS_NAME LIKE 'Microsoft Windows 10%' 
  AND OSUPGRADE_READINESS.STATUS = 'Capable'